# .goreleaser.yml
builds:
- main: cmd/orca.go
  binary: orca
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - amd64
  - arm64
  env:
  - CGO_ENABLED=0
  ldflags:
  - -X main.GitTag={{.Tag}} -X main.GitCommit={{.ShortCommit}}
archive:
  name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
  format: tar.gz
  wrap_in_directory: true
  format_overrides:
  - goos: windows
    format: zip
  replacements:
    darwin: macos
