# .travis.yml
language: go
go:
- 1.11.2

services:
- docker

after_success:
- make build
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- export REPO=$DOCKER_USER/orca
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_TAG ; fi`
- echo $REPO:$TAG
- docker build -f Dockerfile -t $REPO:$TAG .
- docker push $REPO
- test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash